### ISSUE TITLE
License declaration?

### ISSUE THREAD

**Issue by jonititan** [cuspaceflight/m3-avionics#1]
License declaration currently missing for this project?

[Hackaday](http://hackaday.com/2017/08/21/open-source-modular-rocket-avionics-package/) has published an article about your project saying it is Open source but there is currently no license listed for the project only for some components.

**Comment by adamgreig** [comment]
Yes, the project is not open source.

**Comment by jonititan** [comment]
Understood so perhaps you should put a copyright declaration on the project?

**Comment by rjw57** [comment]
Those would be covered in individual files. There is not one simple declaration which would cover the entire tree AFAICT.

**Comment by jonititan** [comment]
If you just include in your readme that you recognise the various licenses on components but that you own work is copyright?  It's not really my area.  Just thought your work was interesting.

**Comment by rjw57** [comment]
Sounds sensible. Anyone fancy opening a PR?

**Comment by jonititan** [comment]
I created one.  Hope that's ok.  We'd be interested in hearing from you guys sometime down at Cranfield.
